"""Build the public release bundle.

    python analysis/make_release.py --out release/

The licence status of Nepali statutory text is unresolved (see
`corpus/SOURCES.md`). Government legal texts are typically freely reproducible,
but "typically" is not a licence, and the source aggregator publishes no terms.

So the release carries **everything except the statutory text itself**:

* citation keys, section numbers, headings
* amendment provenance — operation, ordinal, footnote sentence
* validity windows and benchmark items
* SHA-256 of each provision's text, so a rebuild can be verified byte-for-byte
* offsets and lengths, so annotations can be re-anchored
* the harvester, which reconstructs the full corpus from the live source

A verbatim span is replaced by its SHA-256 and length. That keeps the nugget
checkable after a rebuild — hash the candidate span and compare — without
redistributing the text. Anyone who runs the harvester gets the same corpus and
can verify it matches ours by hash.

If the licence is later clarified, `--include-text` produces the full bundle
without changing any identifier.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import date
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

_TEXT_FIELDS = ("text",)
"""Fields holding statutory text verbatim."""


def _audit() -> dict:
    """What the human audit log says, or that no audit has been applied."""
    log = ROOT / "AUDIT" / "audit_log.json"
    if not log.exists():
        return {"items_verified_by_human": 0,
                "summary": "NOT PERFORMED - every item is status=unverified; see "
                           "AUDIT_human_verification_required.md"}
    a = json.loads(log.read_text(encoding="utf-8"))
    c = a["counts"]
    return {"items_verified_by_human": a["items_verified_by_human"],
            "summary": (f"{a['items_with_verdict']} of {a['items_total']} items audited by "
                        f"{a['auditor']} ({a['qualification']}) on {a['applied_at'][:10]}: "
                        f"{c['correct']} correct, {c['incorrect']} incorrect, {c['unsure']} unsure")}


def _digest(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def redact_corpus_row(row: dict) -> dict:
    """Drop statutory text, keep everything that identifies and verifies it."""
    out = dict(row)
    for field in _TEXT_FIELDS:
        text = out.pop(field, "")
        out[f"{field}_sha256"] = _digest(text)
        out[f"{field}_length"] = len(text)

    # Amendment units carry the post-amendment clause text.
    out["amended_units"] = [
        {
            **{k: v for k, v in u.items() if k != "text"},
            "text_sha256": _digest(u.get("text", "")),
            "text_length": len(u.get("text", "")),
        }
        for u in row.get("amended_units", [])
    ]
    # Footnote sentences are editorial apparatus naming the amendment, not
    # statutory text, and they are the provenance a reviewer must be able to
    # check. They are kept.
    return out


def redact_item(item: dict) -> dict:
    """Replace verbatim gold spans with a verifiable digest."""
    out = dict(item)
    out["gold_nuggets"] = [
        (
            {
                "kind": n["kind"],
                "value_sha256": _digest(n["value"]),
                "value_length": len(n["value"]),
            }
            if n["kind"] == "exact"
            else n
        )
        for n in item.get("gold_nuggets", [])
    ]
    return out


def _copy_jsonl(src: Path, dst: Path, fn) -> int:
    dst.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with dst.open("w", encoding="utf-8") as fh:
        for line in src.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            fh.write(json.dumps(fn(json.loads(line)), ensure_ascii=False) + "\n")
            n += 1
    return n


def _version() -> str:
    """The single source of truth for the release version.

    Kept in one file so the manifest, the citation and the git tag cannot
    disagree. A hand-edited version that contradicts its tag makes a dataset
    uncitable: a reader following the citation gets a different corpus from the
    one whose numbers they are checking.
    """
    raw = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", raw):
        raise SystemExit(
            f"VERSION must be MAJOR.MINOR.PATCH, found {raw!r}. "
            "See release/VERSIONING.md for what each part means here."
        )
    return raw


def _stamp_citation(out: Path, version: str) -> None:
    """Write the version and release date into CITATION.cff.

    CITATION.cff is not regenerated by this script (it carries author details
    this script has no business owning), so only the two version-bearing fields
    are rewritten and everything else is left untouched. A citation whose
    version disagrees with its git tag sends a reader to the wrong corpus.
    """
    cff = out / "CITATION.cff"
    if not cff.exists():
        return
    text = cff.read_text(encoding="utf-8")
    today = date.today().isoformat()
    if re.search(r"^version:", text, re.M):
        text = re.sub(r"^version:.*$", f"version: {version}", text,
                      count=1, flags=re.M)
    else:
        # No version field yet: add one after the licence line.
        addition = "\n" + f"version: {version}"
        text = re.sub(r"^(license:.*)$",
                      lambda m: m.group(1) + addition,
                      text, count=1, flags=re.M)
    text = re.sub(r"^date-released:.*$", f"date-released: {today}", text,
                  count=1, flags=re.M)
    cff.write_text(text, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description="Build the public release bundle")
    ap.add_argument("--out", type=Path, default=ROOT / "release")
    ap.add_argument(
        "--include-text",
        action="store_true",
        help="include statutory text (only once the licence is confirmed)",
    )
    args = ap.parse_args(argv)

    out = args.out
    if out.exists():
        # Clear the CONTENTS, never the directory itself. The release folder is
        # a git repository with its own remote, and rmtree on it deletes the
        # history along with the files: on Windows it fails partway through with
        # a PermissionError on a packed object, leaving a half-deleted .git that
        # is worse than either outcome.
        # Files this script does not generate but the release needs. Clearing
        # them leaves a published repository with no licence and no README
        # until someone notices, and `git status` shows the deletion among a
        # hundred other staged changes.
        keep = {
            ".git", ".github", ".gitignore", "LICENSE", "README.md",
            "CITATION.cff", "CHANGELOG.md", "CONTRIBUTING.md", "VERSIONING.md",
            "AUDIT_human_verification_required.md",
            "NEPVERSA_preprint.pdf", "REPRODUCE.md",
        }
        for child in out.iterdir():
            if child.name in keep:
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
    out.mkdir(parents=True, exist_ok=True)

    corpus_fn = (lambda r: r) if args.include_text else redact_corpus_row
    item_fn = (lambda r: r) if args.include_text else redact_item

    totals = {"provisions": 0, "items": 0}
    for src in sorted((ROOT / "corpus" / "raw").glob("*.jsonl")):
        totals["provisions"] += _copy_jsonl(src, out / "corpus" / src.name, corpus_fn)
    for src in sorted((ROOT / "benchmark" / "candidates").glob("*.jsonl")):
        totals["items"] += _copy_jsonl(src, out / "benchmark" / src.name, item_fn)

    # Code, docs and provenance travel verbatim.
    for rel in ("src", "tests", "analysis", "configs"):
        shutil.copytree(ROOT / rel, out / rel, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    # `logs/decisions.md` is deliberately NOT released: it records private
    # decisions about the author's separate commercial tool.
    for rel in ("corpus/SOURCES.md", "benchmark/guidelines.md",
                "logs/PROVENANCE.md", "logs/citations_verified.md",
                "logs/lit_notes.md", "scripts_regenerate.sh",
                # Verdicts only; the sheet itself quotes statutory text.
                "AUDIT/audit_log.json",
                "paper/shared/references.bib", "paper/shared/numbers.json"):
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / rel, dst)

    version = _version()
    (out / "RELEASE_MANIFEST.json").write_text(
        json.dumps(
            {
                "version": version,
                "released": date.today().isoformat(),
                "statutory_text_included": args.include_text,
                "provisions": totals["provisions"],
                "benchmark_items": totals["items"],
                # The version is not a quality claim: read this field, not the
                # version number, to learn whether anything has been audited.
                # Read from the audit log written by analysis/audit_sheet.py,
                # never typed: CI fails if more items say `verified` than this.
                "items_verified_by_human": _audit()["items_verified_by_human"],
                "verification_status": _audit()["summary"],
                "redaction": "text replaced by sha256 + length; rebuild with src/nepversa/harvest.py",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    _stamp_citation(out, version)

    print(json.dumps(totals, indent=2))
    print(f"release written to {out}")
    print(f"statutory text included: {args.include_text}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
