"""Flag text that may be too close to a cited source, for Nikhil to fix.

    python analysis/originality_check.py

Writes `logs/originality_report.md`. PAPER_PLAN.md §1 rule 7 governs what this
is for: it exists to catch **accidental** copying and too-close paraphrase so
that they can be rewritten honestly. It is not an "AI detector", and its output
must never be used to disguise authorship. AI assistance is disclosed openly in
the Author Note.

Method: every run of `WINDOW` consecutive words in the manuscript is compared
against the abstracts of the cited works held in `logs/citations_verified.md`
and `paper/shared/references.bib`. A shared run that long is rarely coincidence
outside a quotation, so each hit is reported with its location for a human to
judge.

Limits, stated plainly: this compares against the abstracts and titles we hold
locally, not against the full text of every cited paper, and not against the
web. It cannot clear a manuscript. A formal check (Turnitin or iThenticate,
through the campus or TU Central Library) remains necessary, and most journals
run their own.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WINDOW = 8
"""Words per shingle. PAPER_PLAN.md §9.4 item 5 specifies runs of >= 8."""


def _normalise(text: str) -> list[str]:
    """Lowercase word tokens, punctuation dropped, order preserved."""
    return re.findall(r"[a-z0-9]+", text.lower())


def _shingles(words: list[str], n: int = WINDOW) -> dict[tuple[str, ...], int]:
    """Every n-gram with the index of its first occurrence."""
    out: dict[tuple[str, ...], int] = {}
    for i in range(len(words) - n + 1):
        out.setdefault(tuple(words[i : i + n]), i)
    return out


def _manuscript_text() -> str:
    """The manuscript as prose, from the sections rather than the .docx.

    The sections are the source of truth and carry no page furniture, so a
    hit can be reported against a file and a line the author can open.
    """
    parts = []
    for md in sorted((ROOT / "paper/apa/sections").glob("*.md")):
        parts.append(f"\n@@FILE {md.name}\n" + md.read_text(encoding="utf-8"))
    return "".join(parts)


def _source_texts() -> dict[str, str]:
    """Titles and abstracts of the cited works, as far as we hold them."""
    sources: dict[str, str] = {}

    bib = ROOT / "paper/shared/references.bib"
    if bib.exists():
        raw = bib.read_text(encoding="utf-8")
        for entry in re.finditer(r"@\w+\{([^,]+),(.*?)\n\}", raw, re.S):
            key, body = entry.group(1), entry.group(2)
            fields = []
            for field in ("title", "abstract", "booktitle", "journal"):
                m = re.search(rf"{field}\s*=\s*\{{(.+?)\}},?\s*\n", body, re.S)
                if m:
                    fields.append(m.group(1))
            if fields:
                sources[key] = " ".join(fields)

    notes = ROOT / "logs/citations_verified.md"
    if notes.exists():
        sources["logs/citations_verified.md"] = notes.read_text(encoding="utf-8")

    return sources


def main() -> int:
    text = _manuscript_text()

    # Track which section each word came from, so a hit can name a file.
    file_at: list[str] = []
    words: list[str] = []
    current = "(front matter)"
    for line in text.splitlines():
        if line.startswith("@@FILE "):
            current = line[len("@@FILE ") :].strip()
            continue
        # A fenced block or an inline quotation is not a paraphrase problem.
        for w in _normalise(line):
            words.append(w)
            file_at.append(current)

    manuscript = _shingles(words)
    hits: list[tuple[str, str, str]] = []

    for key, source in _source_texts().items():
        src = _shingles(_normalise(source))
        for gram in manuscript.keys() & src.keys():
            i = manuscript[gram]
            hits.append((file_at[i], key, " ".join(gram)))

    hits.sort()

    lines = [
        "# Originality self-check",
        "",
        f"Generated by `analysis/originality_check.py` on {date.today().isoformat()}.",
        "",
        f"Every run of {WINDOW} or more consecutive words shared between the "
        "manuscript sections and the titles, abstracts and verification notes "
        "of the cited works. A shared run this long is rarely coincidence "
        "outside a quotation.",
        "",
        "**What this is for.** Catching accidental copying and too-close "
        "paraphrase so that they can be rewritten (PAPER_PLAN.md §1 rule 7). "
        "It is not an AI detector and must never be used to disguise "
        "authorship; AI assistance is disclosed in the Author Note.",
        "",
        "**What it cannot do.** It compares against the abstracts and titles "
        "held locally, not the full text of the cited papers and not the web, "
        "so it cannot clear the manuscript. A formal check (Turnitin or "
        "iThenticate via the campus or TU Central Library) is still required, "
        "and most journals run their own.",
        "",
    ]

    if not hits:
        lines += [
            f"## Result: no shared runs of {WINDOW}+ words",
            "",
            "No passage in the manuscript shares an "
            f"{WINDOW}-word run with any source checked. This is a clean "
            "result for the comparison performed, not a clearance.",
            "",
        ]
    else:
        lines += [f"## Result: {len(hits)} passage(s) to review", "",
                  "| Section | Source | Shared run |", "|---|---|---|"]
        for section, key, gram in hits:
            lines.append(f"| `{section}` | `{key}` | {gram} |")
        lines += [
            "",
            "Review each one. If it is a quotation, put it in quotation marks "
            "with a page or section locator. If it is a paraphrase, rewrite it "
            "in your own words. If it is a technical term of art that has only "
            "one phrasing, note that here and leave it.",
            "",
        ]

    out = ROOT / "logs/originality_report.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(hits)} shared run(s) of {WINDOW}+ words -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
